version: '3.7'

services:

    webservers:
       image: nginx
       ports:
       - 9090:80/tcp
       
    appservers:
       image: tomcat
       ports:
       - 8085:8080/tcp   
      
    database:
       image: redis
       ports:
       - 6379:6379/tcp
       
    
